#!/bin/bash
#setup-inventory.sh
#Generates the Ansible inventory file from user input.
#This script is cloud-agnostic: it works with any provider (GCP, AWS, Azure, etc.)
#or local VMs (VirtualBox, bare metal).
#
#Usate: chmod +x setup-inventory.sh && ./setup-inventory.sh
#Output: inventory/hosts.yml (gitignored)
#
#


set -e

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║     K8S Fullstack Base — Inventory Setup             ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Enter the IPs of your VMs.                          ║"
echo "║  All VMs must be Debian/Ubuntu-based with SSH        ║"
echo "║  access configured.                                  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""




read -p " K8S Master node IP:   " MASTER_IP
read -p " K8S Worker 1 IP:      " WORKER1_IP
read -p " K8S Worker 2 IP:      " WORKER2_IP
read -p " Nginx Proxy IP:       " NGINX_IP
echo ""
read -p " SSH user [default: ansible]: " SSH_USER
SSH_USER=${SSH_USER:-ansible}


if [[ -z "$MASTER_IP" || -z "$WORKER1_IP" || -z "$WORKER2_IP" || -z "$NGINX_IP" ]]; then
	echo ""
	echo " ERROR: All IPs are required."
	exit 1
fi

mkdir -p inventory

cat > inventory/hosts.yml <<EOF
# Ansible inventory - generated by setup-inventory.sh
# Do NOT commit this file to Git (it is gitignored).
# To regenerate, run: ./setup-inventory.sh
---
all:
  vars:
    ansible_user: ${SSH_USER}
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:

    k8s_master:
      hosts:
        master1:
          ansible_host: ${MASTER_IP}


    k8s_workers:
      hosts:
        worker1:
          ansible_host: ${WORKER1_IP}
        worker2:
          ansible_host: ${WORKER2_IP}

     
    # Group that includes all K8S nodes (master + workers).
    # Used by playbooks that target the entire cluster (Docker, K8S prereqs).
    k8s_cluster:
      children:
        k8s_master:
        k8s_workers:
    
    # Nginx reverse proxy (external to the K8S cluster).
    proxy:
      hosts:
        nginx1:
          ansible_host: ${NGINX_IP}
EOF

echo ""
echo " Inventory generated at: inventory/hosts.yml"
echo ""
echo " Verify with:"
echo "   ansible-inventory --list"
echo "   ansible all -m ping"
echo ""
