---
  - hosts: all
    become: true
    tags: [bootstrap]
    roles:
      - bootstrap
  
  - hosts: proxy
    become: true
    tags: [nginx]
    roles:
      - nginx

  - hosts: k8s_cluster
    become: true
    roles:
      - role: docker
        tags: [docker] 
      - role: k8s-prereqs
        tags: [k8s_prereqs]

  - hosts: k8s_master
    become: true
    tags: [k8s_master]
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf    
    roles:
      - k8s-master

  - hosts: k8s_workers
    become: true
    tags: [k8s_workers]
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf      
    roles:
      - k8s-workers

  - hosts: k8s_master
    become: true  
    tags: [k8s_ingress]
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf  
    roles:
      - k8s-ingress

  - hosts: k8s_master
    become: false
    tags: [app-web]
    roles:
      - app-web
...
