---
    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
      listen: "restart containerd"

    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        state: restarted
      listen: "restart kubelet"
...
