---
- name: Install Docker
  hosts: k8s_cluster
  vars:
    deps_packages:
      - ca-certificates
      - curl

    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin  
  tasks:

  - name: Install prerequisites
    ansible.builtin.apt:
      name: "{{ deps_packages }}"
      state: present
      update_cache: yes    
    tags: [install, prerequisites]


  - name: Modify privileges
    ansible.builtin.file:
      mode: 0755
      path: /etc/apt/keyrings
      recurse: yes
      state: directory


  - name: Download Docker GPC key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: a+r

  - name: Get distribution release
    ansible.builtin.shell:  . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"  
    register: variable_output
    changed_when: false
    failed_when: variable_output.stdout == ""
      
  - name: Add the repository to apt sources
    ansible.builtin.copy:
      dest: /etc/apt/sources.list.d/docker.sources
      content: |
         Types: deb
         URIs: https://download.docker.com/linux/debian
         Suites: {{ variable_output.stdout }}
         Components: stable
         Signed-By: /etc/apt/keyrings/docker.asc
      mode: 0644

  - name: Install Docker Engine and Plugins
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name: "{{ docker_packages }}"
    tags: [install, docker]

  - name: Docker service
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes
    tags: [configure, docker]

  - name: Verify Docker installation
    block:
      - name: Run hello-world container
        ansible.builtin.command: docker run --rm hello-world
        register: output

      - name: Display success
        ansible.builtin.debug:
          msg: "Docker is running correctly!"
        when: "'Hello from Docker!' in output.stdout"   

    rescue:
      - name: Display failure
        ansible.builtin.debug:
          msg: "WARNING: Docker verification failed. Check Docker service status."

      - name: Show Docker services status
        ansible.builtin.command: systemctl status docker
        register: docker_status
        changed_when: false

      - name: Display service status
        ansible.builtin.debug:
          var: docker_status.stdout_lines
    tags: [verify]
...
